### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/core-web-vitals-pagespeed-booster#1]
Please follow the naming conventions showed in the WP Documentation 
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions

- [x]  https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/web-vitals-page-speed-booster.php#L32
 Single Quote in the Hook `add_action('plugins_loaded',  'initiate_web_vital');`

- [x]  Why we are using `web_vital` everywhere while our plugin name is `web_vitals`?

- [x] Same with the Constant Names `WEBVITAL_PAGESPEED_BOOSTER_FILE ` https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/web-vitals-page-speed-booster.php#L17

- [x] Function names:  `web_vital_defaultSettings` has to be like this -> `web_vitals_default_settings`  https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/web-vitals-page-speed-booster.php#L24

- [x]  Incorrect naming convention for Variables `$webVital_settings` has to be like `$web_vitals_settings`  https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/web-vitals-page-speed-booster.php#L23 

- [x]  Incorrect naming convention for Class name `webVitalHelperSection` has to be `Web_Vitals_Helper_Section`
https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/web-vitals-page-speed-booster.php#L42

- [x] Function name `converttoWebp` -> `convert_to_webp` https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/inc/helper-section.php#L3 

- [x] Same with `doUploadWithWebp` https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/inc/helper-section.php#L22

- [ ] Incorrect Spacing and Tabbing https://monosnap.com/file/vXcYJ70yUdhhZ8qBXCNumizEu1qxoy

- [x]  Class name incorrect in multiple instances https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/inc/admin-section.php#L2

- [x] Remove unused code https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/inc/admin-section.php#L62

- [x] `webvital_dashboard_section` -> `web_vitals_dashboard_section`  https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/inc/admin-section.php#L50

- [x]  Escaping URL missing: https://github.com/ahmedkaludi/web-vitals-page-speed-booster/blob/master/inc/admin-section.php#L171

**Comment by Zabi09** [comment]
Pushed in 1.0.1
