### ISSUE TITLE
Fatal Error on Multisite Activation: is_plugin_active_for_network() Undefined

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/core-web-vitals-pagespeed-booster#106]
User facing a fatal error," Fatal error: Uncaught Error: Call to undefined function is_plugin_active_for_network() in /wp-content/plugins/core-web-vitals-pagespeed-booster/includes/functions.php:173"

Reference ticket: https://wordpress.org/support/topic/fatal-error-on-activating-the-plugin/

**Comment by akshaywali** [comment]
pushed in update 1.0.15
