### ISSUE TITLE
Uninstall.php only removes main critical URLs table from database in multisite

### ISSUE THREAD

**Issue by lorthiois** [ahmedkaludi/core-web-vitals-pagespeed-booster#111]
Currently, plugin creates a table for critical urls for each site in the database. The uninstall file only triggers a table drop for the main website and doesn't consider the possibility of a multisite. Currently, other "prefix_cwvpb_critical_urls" tables must be deleted manually to keep the database clean upon uninstall.

Suggested edit (chatgpt):

if (function_exists('is_multisite') && is_multisite()) {
    $original_blog_id = get_current_blog_id();
    $blog_ids = $wpdb->get_col("SELECT blog_id FROM {$wpdb->blogs}");
    
    foreach ($blog_ids as $blog_id) {
        switch_to_blog($blog_id);
        $cached_table = $wpdb->prefix . 'cwvpb_critical_urls';
        $wpdb->query("DROP TABLE `$cached_table`");
    }

    switch_to_blog($original_blog_id);
} else {
    $cached_table = $wpdb->prefix . 'cwvpb_critical_urls';
    $wpdb->query("DROP TABLE `$cached_table`");
}

**Comment by Sanjeevsetu** [comment]
Hi @lorthiois 

Thanks for reporting it. Sure, We will make it change

**Comment by akshaywali** [comment]
pushed in update  1.0.16
