### ISSUE TITLE
wp-content/gravatars folder not removed upon uninstall

### ISSUE THREAD

**Issue by lorthiois** [ahmedkaludi/core-web-vitals-pagespeed-booster#112]
This plugin creates the wp-content/gravatars folder and populates it with cached avatar images, but doesn't remove it when uninstalling.

**Comment by Sanjeevsetu** [comment]
Hi @lorthiois 

Thanks for reaching to us. We will check it and will fix it

**Comment by akshaywali** [comment]
pushed in update  1.0.16
