### ISSUE TITLE
Robots.txt error appears when you we enable our CWV plugin.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/core-web-vitals-pagespeed-booster#114]
Ref ticket:- https://magazine3.in/conversation/202669?folder_id=3

Description:-
When we enable the CWV plugin Robots.txt error appears in PageSpeed Insights.

Issue screenshot:-
https://prnt.sc/niLcmmXSuOBt

**Comment by Sdaud1950** [comment]
same issue with this user : https://magazine3.in/conversation/204094?folder_id=29

**Comment by akshaywali** [comment]
pushed in update  1.0.16
