### ISSUE TITLE
New feature: Automatic Resizing to fix Properly Size Image issue.

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/core-web-vitals-pagespeed-booster#118]
We can do this with the help of the content width variable.
It'll help us to fix the PSI Properly Size Image issue.

**Comment by akshaywali** [comment]
pushed in 1.0.17

**Comment by mohammed-qutubuddin** [comment]
Properly size images still appear for a user, we need to improve it.

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/core-web-vitals-pagespeed-booster/commit/8c88e32c043f48178a8d4104759f84334c504d5c

**Comment by akshaywali** [comment]
pushed in 1.0.22
