### ISSUE TITLE
Generates bug when activating Critical CSS optimisation 

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/core-web-vitals-pagespeed-booster#124]
When enabling critical css optimisation option, it generates few db errors.

Reference ticket -: https://magazine3.in/conversation/223332?folder_id=23

**Comment by akshaywali** [comment]
Need user wp details for proper testing.

**Comment by akshaywali** [comment]
After investigating more , it is found that somehow the table is modifieds  by backup or manually . As of now we are  closing this ticket until further details are shared.
