### ISSUE TITLE
Code Improvement

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/core-web-vitals-pagespeed-booster#125]
- [x] Every response message must be escaped includes\css\critical_css.php Linne: 871, 873, 877 and check the same in everywhere
- [x] loop validation missing includes\css\google-fonts.php Line: 61 and check others
- [x] function must have a prefix outside class 'download_google_font'. 'run_CWV_lazy_load' check others as well
- [x] direct echo inside this function 'cwvpsb_delay_js_load'
- [x] check this and validate with nonce
- [x] Remove all commented code
- [x] wrong escaping : \includes\functions.php Line : 17,
- [x] sanitization missing : \includes\functions.php Line : 105,
- [x] change all json_encode to wp_json_encode
- [x] change all _e to esc_html_e
- [x] No need to create two nonce for one file. \includes\functions.php Line : 205, and "cwvpsb_showdetails_data_nonce" key is same for array and nonce, it could conflict. remove it.
- [x] Create minified version of css and js. connected to define( 'SCRIPT_DEBUG', true );
- [x] Improved it, it could give warnings : \includes\functions.php Line : 323,339
- [x] Improved it, no need to pass <style> inside wp_add_inline_style : \includes\functions.php Line : 365
- [x] Duplicate line \includes\admin\settings.php Line : 635/636, 
- [x] Sanitization missing \includes\admin\settings.php Line : 1083
- [x] Escape missing \includes\admin\settings.php Line : 799,803,805,807,815,825,835,836,837,838,845,846,847,848,853,854,855,856,866-869,875-877,887-890,895-898,908-911,917-920,929,1158,1163,1164,
- [x] improvemnt in \includes\admin\newsletter.php sanitization and escap

**Comment by akshaywali** [comment]
pushed in 1.0.17
