### ISSUE TITLE
Page not displayed if a GET parameter is attached to the URL

### ISSUE THREAD

**Issue by kzapatista** [ahmedkaludi/core-web-vitals-pagespeed-booster#128]
Basically, the plugin works very well – thank you very much for that. 

However, an error occurs if a **Get parameter is attached to the URL**. The page will then not be displayed at all and will remain completely white.
For example, if we link a website from Facebook or Instagram, Facebook automatically appends a GET parameter to the link (fbclid). This prevents the page from being accessed.

E.g. https://www.jap-fotografie.de/?fbclid=IwAR31ZER4JRMjF6WTetyE851ONmDzV3_8zY08YIdXy0yz_ecNqTgKGTh1iJU --> does not work
https://www.jap-fotografie.de --> works. 
How can I solve this problem? Linking to our pages via social media platforms is extremely important.
Thanks an regards
Karina

**Comment by Sanjeevsetu** [comment]
Hi @kzapatista 

Sorry for the late response. We got your details information on support channel. We look at it and update you very soon.
