### ISSUE TITLE
Need improvement in Image lazy load

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/core-web-vitals-pagespeed-booster#131]
1. Some images are not getting load if we enable lazyload
2. As the lazyload works on scroll or mouse move, but after scrolling it takes more than 4-5 seconds to load images.
3. in mobile if we click on magnifier icon to zoom the image, the image getting failed to open 
Reference Screenshot: https://prnt.sc/az-E9BiaPPvO
4. Webstory design break

**Comment by akshaywali** [comment]
pushed in version 1.0.18
