### ISSUE TITLE
Can't over ride the width of .cwvpsb_iframe due to the important property used

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/core-web-vitals-pagespeed-booster#132]
Our plugin added the below CSS
.cwvpsb_iframe {
    max-width: 600px !important;
}

Here we are using important property, and due to this we cant override this width

The user embedding the YouTube video and previously the video width is big but after installing our plugin the width is decreased,

**Comment by akshaywali** [comment]
pushed in update 1.0.19
