### ISSUE TITLE
When activating the plugin it causes the homepage to display Chinese characters and slows down the backend.

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/core-web-vitals-pagespeed-booster#133]
When I activate the CVW plugin, it causing the homepage to display in Chinese characters and slowing down the backend. 
This issue is coming from Yoast SEO plugin and when I deactivate the Yoast plugin, the issue is solved.

Ref. ticket : https://magazine3.in/conversation/81026?folder_id=11

**Comment by akshaywali** [comment]
pushed in version 1.0.18
