### ISSUE TITLE
NOTICE: PHP message: PHP Warning:  Undefined variable $img_srcset

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/core-web-vitals-pagespeed-booster#141]
NOTICE: PHP message: PHP Warning:  Undefined variable $img_srcset in /var/www/wptbox/wp-content/plugins/core-web-vitals-pagespeed-booster/includes/images/convert-webp.php on line 259"
PHP message: PHP Warning:  Undefined array key 1 in /var/www/wptbox/wp-content/plugins/core-web-vitals-pagespeed-booster/includes/images/convert-webp.php

**Comment by akshaywali** [comment]
pushed in update 1.0.19
