### ISSUE TITLE
Parsing error: Missing ',' or '}' in structured data due data IMG

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/core-web-vitals-pagespeed-booster#142]
Parsing error: Missing ',' or '}' in structured data
Reference Screenshot: https://prnt.sc/srzZt81kXDbM

**Comment by akshaywali** [comment]
This issue can not be recreated, so will be closing this ticket. If this issue happens again in future will reopen the ticket.
