### ISSUE TITLE
Warnings: PHP Deprecated: mb_convert_encoding() 

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/core-web-vitals-pagespeed-booster#153]
One user reported this issue that on debug.log getting this warnings,

“PHP Deprecated: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in C:\wamp64\www\paduli.dmi\wp-content\plugins\core-web-vitals-pagespeed-booster\includes\images\convert-webp.php on line 88“.

Reference ticket: https://wordpress.org/support/topic/php-deprecated-mb_convert_encoding-2/

**Comment by akshaywali** [comment]
pushed in update 1.0.21
