### ISSUE TITLE
Critical Error with PHP version 8.0.17

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/core-web-vitals-pagespeed-booster#38]
Critical Error with PHP version 8.0.17
Recreated on localhost: https://prnt.sc/LvDKrolqEYto

Benjamin user facing this issue

**Comment by Marghoob123** [comment]
Another user had the same issue when we enable the "Lazy Load" option in our plugin.

Joseph Emeka user facing this issue.

Helpscout Url: https://secure.helpscout.net/conversation/1813918163/230565?folderId=5044124
