### ISSUE TITLE
Need to add "Video Lazy Load Off"

### ISSUE THREAD

**Issue by Marghoob123** [ahmedkaludi/core-web-vitals-pagespeed-booster#57]
Need to add "Video Lazy Load Off"

When our plugin is enabled the Youtube Embeds are not able to pick, due to improper format.
https://prnt.sc/m3JeVLMXKRPS

When our plugin is disabled, it is working.
https://prnt.sc/yiEZZcE5lgYQ

**Comment by akshaywali** [comment]
This issue is fixed the following ticket
https://github.com/ahmedkaludi/core-web-vitals-pagespeed-booster/issues/105
