### ISSUE TITLE
Issue with Elementor SVG

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/core-web-vitals-pagespeed-booster#58]
If our plugin is active then the user unable to upload the proper elementor SVG
Reference Video: https://www.loom.com/share/64c34d3ddf354848a53897182717fc3a

Helpscout URL: https://secure.helpscout.net/conversation/1889661730/243370?folderId=1060556

**Comment by akshaywali** [comment]
Code Pushed https://github.com/ahmedkaludi/core-web-vitals-pagespeed-booster/commit/5fc96b399193b7a9f958a807f256fd95fbcfde08

**Comment by akshaywali** [comment]
update pushed in 1.0.11
