### ISSUE TITLE
When the CWV plugin is activated, the Wocommerce payment page is not working.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/core-web-vitals-pagespeed-booster#77]
When the CWV plugin is enabled, the user is unable to make a payment on their mobile device via the Wocommerce payment page. 

Ref screenshot :https://prnt.sc/kqIRDyJzbaMw , https://prnt.sc/tWN1Nnr-NIfG 

Ref ticket : https://magazine3.in/conversation/101714?folder_id=29

**Comment by Sasirekhamarella** [comment]
Same issue: https://wordpress.org/support/topic/checkout-page-dont-work/

**Comment by sajandara** [comment]
The user is facing a same issue
https://magazine3.in/conversation/102657?folder_id=27

**Comment by akshaywali** [comment]
pushed in version 1.0.11
