### ISSUE TITLE
Conflict with the  Google reCAPTCHA v3 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/core-web-vitals-pagespeed-booster#82]
When we add a contact form to our website using the WP contact form, when we include the Google reCAPTCHA v3, but it returns an error in the console when we use the CWV plugin.

Ref screenshot: https://prnt.sc/fistxGYLu7c5

Ref Ticket:https://magazine3.in/conversation/126627?folder_id=29

**Comment by akshaywali** [comment]
pushed in update 1.0.12
