### ISSUE TITLE
Parse error: syntax error, unexpected ')' 

### ISSUE THREAD

**Issue by Melak12** [ahmedkaludi/core-web-vitals-pagespeed-booster#87]
When I try to activate this plugin, I am getting the following error: 

![image](https://user-images.githubusercontent.com/45941116/234017931-b76ef21a-fdfc-49d1-bdfa-1666b50c09d7.png)

My WordPress version: 6.1.1

**Comment by akshaywali** [comment]
pushed in update 1.0.14
