### ISSUE TITLE
Need to add an option to exclude lazyloading

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/core-web-vitals-pagespeed-booster#91]
There is a need to add an option to remove/exclude any image from lazyload.

references ticket -: https://magazine3.in/conversation/150450?folder_id=23

**Comment by akshaywali** [comment]
Add class **cwvlazyload_exclude** to the image which you want to be excluded from the  lazyload feature

**Comment by akshaywali** [comment]
pushed in update 1.0.19
