### ISSUE TITLE
Image on site disappears when activate the plugin

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/core-web-vitals-pagespeed-booster#96]
When activating the plugin, the images  of the site got disappears.

Reference ticket -: https://magazine3.in/conversation/159785?folder_id=23

**Comment by akshaywali** [comment]
Issue fixed with the commit  https://github.com/ahmedkaludi/core-web-vitals-pagespeed-booster/commit/e4ae53cb30093e754ded46e3b1c2e725b7a8e6d0

**Comment by akshaywali** [comment]
pushed in update 1.0.14
