### ISSUE TITLE
Test with MYSQL v5.5

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/core-web-vitals-pagespeed-booster#97]
user reported the following error: "Table 'saf3w30rk_rk_sa3f3.wDQw3p_cwvpb_critical_urls'."  Also, mentioned that the plugin doesn't work with MySQL v5.5.

Reference ticket at: https://wordpress.org/support/topic/data-base-errors-2/

**Comment by akshaywali** [comment]
pushed in update 1.0.15
