### ISSUE TITLE
Error in core-web-vitals-pagespeed-booster Plugin.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/core-web-vitals-pagespeed-booster#99]
User reported Warning: call_user_func() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in C:\laragon\www\htbuilder\wp-content\plugins\core-web-vitals-pagespeed-booster\includes\cache\cache-class.php on line 572

Here is the reference ticket: https://wordpress.org/support/topic/bug-409/

**Comment by akshaywali** [comment]
pushed in update 1.0.14
